url: https://paaraspurohit.github.io
baseurl: /blue-owl-tutoring-site/

# Site settings
title: Blue Owl Learning
email: blueowllearningc@gmail.com
description: "A non-profit free tutoring organization for K-12 education, with the mission of making academic success accessible to everyone."


# Team names, titles and social links
people:
- name: Paaras Purohit
  pic: 1
  position: Lead Developer, Director of Outreach

- name: Emaad Mir
  pic: 2
  position: President

- name: Dinesh Sahai
  pic: 3
  position: Senior Administrator, Event Coordinator

- name: Swarith Vaddi
  pic: 1
  position: Senior Administrator, Tutor Coordinator

- name: Ankit Pulivendula
  pic: 2
  position: Administration Management, Developer

- name: Rishi Bansal
  pic: 3
  position: Director of Marketing
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty