url: https://paaraspurohit.github.io
baseurl: /blue-owl-tutoring-site/

# Site settings
title: Blue Owl Learning
email: blueowllearningc@gmail.com
description: "A non-profit free tutoring organization for K-12 education, with the mission of making academic success accessible to everyone."


# Team names, titles and social links
people:
- name: Paaras Purohit
  pic: 1
  position: Lead Developer, Director of Outreach

- name: Emaad Mir
  pic: 2
  position: President

- name: Dinesh Sahai
  pic: 3
  position: Senior Administrator, Event Coordinator

- name: Swarith Vaddi
  pic: 4
  position: Senior Administrator, Tutor Coordinator

- name: Ankit Pulivendula
  pic: 5
  position: Administration Management, Developer

- name: Rishi Bansal
  pic: 6
  position: Director of Marketing

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/@blueowllearning
  - title: gmail
    url: mailto:blueowllearningc@gmail.com

# Postal address (add as many lines as necessary)
address:
  - line: 16825 Wren Haven Way
  - line: Apt. 3

# Build settings
markdown: kramdown
permalink: pretty